### PR TITLE
Update media_entity to current HEAD

### PR DESCRIPTION
**Pull request by dawehner**
This is needed in order to be able to install media_entity with HEAD.

### CODE REVIEW

**Comment by slashrsm** [comment]
Hm... most of this fixes should already be in (if not all).

**Comment by dawehner** [comment]
Mh,  haven't thought that you use the drupal.org issue queue mhhh what about at least closing the issues on github?

**Comment by slashrsm** [comment]
We use PRs on github but we have policy that we always open corresponding issues on d.o.

I created patch for "controllers to handlers" shortly before you posted this PR. All other fixes have been in the codebase a while already. 

I apologize for the inconvenience.

**Comment by slashrsm** [comment]
I'll add DEVELOPMENT.md to follow standards of all other media modules.

**Comment by slashrsm** [comment]
Thank you for your contribution!

**Comment by dawehner** [comment]
No worries. Just ensure that you mirror often enough, which was the reason why most of my changes had to be made.

**Comment by slashrsm** [comment]
Will do. It there any ellegant way to automate this?

**Comment by dawehner** [comment]
Well, you could create a git hook which pushes to both removes all the time. Beside that I don't know a really elegant solution.

**Pull request closed without merging**
