### PR TITLE
Bundle try/catch is unnecessary?

### PR DESCRIPTION
**Pull request by saltednut**
Unsure why this is showing a null error during Media Entity save. If I remove it, the Media entity saves correctly.

### CODE REVIEW

**Comment by slashrsm** [comment]
This validate uses media type plugin to validate entity before saving. Which media type is used when you get that error?

**Comment by saltednut** [comment]
All Media types provided by Pinkeye were tested and experienced the same
error when saving.

On Thu, Aug 6, 2015 at 9:28 AM, Janez Urevc notifications@github.com
wrote:

> This validate uses media type plugin to validate entity before saving.
> Which media type is used when you get that error?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupal-media/media_entity/pull/48#issuecomment-128391790
> .

## 

_Brant Wynn_Technical Lead, Presales | _Acquia
http://www.acquia.com/?utm_source=Email&utm_medium=Signature&utm_content=Acquia.com&utm_campaign=Acquia%2BEmail%2BSignature_
_O:_ +1 617-588-9933 | _M:_ +1 312-607-9430 | @brantwynn
http://twitter.com
Demo Drupal as an Enterprise-ready solution http://acquia.com/downloads/df

Start Building Drupal Sites on Acquia Cloud for Free!
http://acquia.com/free

**Comment by slashrsm** [comment]
Hm... This is strange. I tested all bundles in media_pinkeye today and they all saved w/o any errors. Also confirmed validation works as expected (wrong tweet url detected for example). Can you provide a list of steps that led you to the error and paste the error message?

**Comment by slashrsm** [comment]
Validation is now handled through constraints. This is not relevant any more I believe. Fell free to open new issue (preferably on d.o) if you experience any other problems.

**Pull request closed without merging**
